name: Terraform 2 tire project deployment
run-name : ${{ github.actor }} is creating a new deployment

on:
  push: 
    branches: [ main ]
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: ap-south-1
    - name: Terraform Init
      run: terraform init
      working-directory: ./module
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./module
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./module
