name: Terraform 2 tire project deployment
run-name : ${{ github.actor }} is creating a new deployment

on:
  push: 
    branches: [ main ]
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./module
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./module
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./module
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./module