name : 2 tire application deploy
run-name : ${{ github.actor }} this will create new build

on:
    push:
        branches:
            - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug - List files
        run: ls -la
        working-directory: ./home/runner/work/Project2-Implementation-2-Tier-Architecture-in-AWS-using-Terraform
      
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform